### ISSUE TITLE
Support generic superclass @Id for composed endpoints

### ISSUE THREAD

**Issue by feroult** [feroult/yawp#22]

**Comment by luanpotter** [comment]
Shouldn't this be working already? We are using `ReflectionUtils.getFieldsRecursively` to find the @Id field...

**Comment by feroult** [comment]
@daniloPereiraDeluca tried and it didn't work.

**Comment by danilodeLuca** [comment]
The problem is that it try to get the endpoint from declared field class, not from the child class

**Comment by feroult** [comment]
71726b765557751e8ed35b5a34ee50e1ea6f827f
