### ISSUE TITLE
invalid json query using boolean 

### ISSUE THREAD

**Issue by danilodeLuca** [feroult/yawp#24]
yawp('/entity').where(['availble', '=','true']).list(function(l){console.log(l)})

Stack

java.lang.RuntimeException: Invalid json value: true
[INFO] 	at io.yawp.repository.query.DatastoreQueryOptions.getJsonObjectValue(DatastoreQueryOptions.java:94)
[INFO] 	at io.yawp.repository.query.DatastoreQueryOptions.parseSimpleCondition(DatastoreQueryOptions.java:125)
[INFO] 	at io.yawp.repository.query.DatastoreQueryOptions.parseCondition(DatastoreQueryOptions.java:111)
[INFO] 	at io.yawp.repository.query.DatastoreQueryOptions.<init>(DatastoreQueryOptions.java:33)
[INFO] 	at io.yawp.repository.query.DatastoreQueryOptions.parse(DatastoreQueryOptions.java:27)

**Comment by feroult** [comment]
Ok for 1.2.5
