### ISSUE TITLE
Support multi-part paths for Endpoints

### ISSUE THREAD

**Issue by feroult** [feroult/yawp#54]
For example:

``` java
@Endpoint(path = "/store/orders")
public class Order
```

This will be useful to organize APIs into a tree-like structure.

**Comment by luanpotter** [comment]
Would this have the same effect as nested resources (with @ParentId)? Or is it something else?

**Comment by feroult** [comment]
This is something else. This is just a prefix for all routes belonging to this endpoints, including custom actions.

I haven't thought yet about the implications if the endpoint has a ```@ParentId```.  But it seems that this prefix can't be mixed with the Parent/Child routes.
