### ISSUE TITLE
After action method add assync task 

### ISSUE THREAD

**Issue by danilodeLuca** [feroult/yawp#73]
Its similar to pipe behavior, but its linked to a Action call.

Exemple:

Action Method
- addContact() -> This will add one contact (name, email) to user`s contact list, when adding an contact it should send email to the new contact.
  The problem: This action method is sync, and i dont want to send email in a sync call and i want to assign the sending email to this method("addContact");

Maybe adding this to a task queue ....

**Comment by luanpotter** [comment]
There is already an API to call any action asynchronously. It was something like `/endpoint/id/action/async`. It immediately returns an id that can be polled later for the status and response. I don't remember right know how to do it, but @feroult will remember.

**Comment by feroult** [comment]
@luanpotter I think that in this case he wants to do some sync stuff and then fork an async method to send the email.

@danilodeLuca My suggestion for now is to use QueueService directly (are you doing this?). Encapsulate the parts that use the Appengine API to make it easier to remove the dependency if necessary.

I'm thinking about a way to create an async wrapper without losing important options that the QueueService provides.
