### ISSUE TITLE
YAWP! JS Class/Extending (help needed)

### ISSUE THREAD

**Issue by feroult** [feroult/yawp#95]
Support a  new way to create endpoint classes by subclassing the default `yawp` function.

Think about how to deal with ES5 / ES6 support.

For example:

```javascript
class Person extends yawp('/people') {
	static active() {
		return Person.where({}).list;
	}

	activate() {
		this.active = true;
		this.save();
	}
}
```

All the other `yawp` methods still apply:

```javascript
new Person({}).save().destroy();
Person.create({});
Person.update({});
```

Many possibilities...

**Comment by luanpotter** [comment]
I believe one would just need to do something like this: http://stackoverflow.com/a/38016336/1217989

**Comment by feroult** [comment]
Yeah. I started something like this, take a look in this [file/branch](https://github.com/feroult/yawp/blob/new-client/yawp-client/test/yawp.spec.js)

**Comment by feroult** [comment]
This is already integrated in master. We just need to put up some documentation for the new client.
